# -*- coding: utf-8 -*-
"""Project_ASI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwXtW6CPx4SHyw9BOEwYZ1S_ozMRsiA6
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

# DATELE (EDA)
# setul de date CIFAR-10
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalizam pixelii sa fie intre 0 si 1
train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['avion', 'automobil', 'pasăre', 'pisică', 'cerb',
               'câine', 'broască', 'cal', 'vapor', 'camion']

# afisam imaginile , 10 avem
plt.figure(figsize=(10,2))
for i in range(10):
    plt.subplot(1,10,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i])
    plt.xlabel(class_names[train_labels[i][0]])
plt.show()

# MODELUL
# Construim o retea CNN  (Baseline)
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10)) # 10 clase finale

# Compilam modelul
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# 3. ANTRENAREA (Baseline - Fara AIMD inca)
print("Incepe antrenarea :")
history = model.fit(train_images, train_labels, epochs=10,
                    validation_data=(test_images, test_labels))

# 4. REZULTATELE
plt.figure(figsize=(12, 4))

# Grafic
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Acuratețe Antrenare')
plt.plot(history.history['val_accuracy'], label='Acuratețe Validare')
plt.xlabel('Epoci')
plt.ylabel('Acuratețe')
plt.legend(loc='lower right')
plt.title('Evoluția Acurateței (Baseline)')

# Grafic Pierdere (Loss)
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Loss Antrenare')
plt.plot(history.history['val_loss'], label='Loss Validare')
plt.xlabel('Epoci')
plt.ylabel('Loss')
plt.legend(loc='upper right')
plt.title('Evoluția Erorii (Baseline)')

plt.show()